name: Deploy Client

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
jobs:
  deploy-be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: huyraw/ume_client:latest
          file: ./dockers/client.Dockerfile
          context: .

      - name: ssh key passphrase
        uses: appleboy/ssh-action@master
        with:
          continue-on-error: true
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |-
            sudo docker image prune -af
            sudo docker pull huyraw/ume_client
            sudo docker stop backend_server
            sudo docker rm backend_server
            sudo docker run --detach --name backend_server -p 3000:3000 huyraw/ume_client
